name: Learn docker CI

run-name: ${{ github.actor }} is learning Docker CI

on:
  push:
    branches:
      - main

jobs:
  install-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install make
    #   - shell: bash
    #     run: |
    #       make docker_build
