name: Learn docker CI

run-name: ${{ github.actor }} is learning Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nginx-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Make
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install make
      - name: Build Docker Image
        shell: bash
        run: |
          cd .github/workflows
          make docker_build
      #
      # - name: Docker Login
      #   shell: bash
      #   run: |
      #     make docker_login DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
