name: Learn docker CI

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  install-makefile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install make 
          make --version

      - shell: bash
        run: |
          make docker_build
