name: Learn tf CI

on:
  push:
    branches:
      - main

jobs:
  install-makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Install make
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install make 
          make --version
