name: Learn tf CI
run-name: ${{ github.actor }} is learning tf CI

on:
  push:
    branches:
      - main

jobs:
  install-make:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install make 
          make --version
